project:
  name: bearcar_sd_data_training

paths:
  repo_root: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle"

  unlabeled_images_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/new_unlabeled/images"
  autolabel_labels_out_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/new_unlabeled/labels"
  autolabel_preview_out_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/new_unlabeled/previews"

  train_images_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/train"
  val_images_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/valid"
  train_labels_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/train"
  val_labels_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets/valid"

  data_yaml_out: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/sd_data_and_training/artifacts/data.yaml"
  train_project_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/sd_data_and_training/runs"
  export_out_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/sd_data_and_training/exports"

  hailo_labels_json_out: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/AUTONOMOUS_CODE_SD/models/ball_bucket.json"

classes:
  train_names:
    - blue_ball
    - blue_bucket
    - green_ball
    - green_bucket
    - red_ball
    - red_bucket
    - yellow_ball
    - yellow_bucket

  hailo_display_names:
    - blue ball
    - blue bucket
    - green ball
    - green bucket
    - red ball
    - red bucket
    - yellow ball
    - yellow bucket

autolabel:
  teacher_model: "yolov8s.pt"
  conf: 0.35
  iou: 0.50
  imgsz: 640
  max_det: 60
  save_preview: true

training:
  model: "yolov8m.pt"
  imgsz: 640
  epochs: 120
  batch: 16
  workers: 8
  patience: 30
  device: "0"
  run_name: "ball_bucket_vnext_m"

evaluation:
  split: "val"
  conf: 0.25
  iou: 0.60

hailo:
  detection_threshold: 0.50
  max_boxes: 200

roboflow:
  enabled: false
  api_key_env: "ROBOFLOW_API_KEY"
  workspace: "balle"
  project: "project1-cvmwt"
  version: 10
  format: "yolov8"
  download_dir: "C:/Users/hogwi/OneDrive/VSCode GitHub Repos/Stuff-for-autonomous-vehicle/RoboFlowDatasets"
